// Capture real screenshots + a short video tour of the running Northbound app.
//
//   NB_BASE=http://localhost:8090 NB_USER=admin NB_PASS=northbound \
//   node playwright/capture-media.mjs
//
// Output: ../docs/media/screenshots/*.png  and  ../docs/media/northbound-tour.webm
import { chromium } from 'playwright';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { mkdirSync, readdirSync, renameSync, rmSync } from 'node:fs';

const BASE = process.env.NB_BASE ?? 'http://localhost:8090';
const USER = process.env.NB_USER ?? 'admin';
const PASS = process.env.NB_PASS ?? 'northbound';

const here = dirname(fileURLToPath(import.meta.url));
const mediaDir = resolve(here, '../../docs/media');
const shotDir = resolve(mediaDir, 'screenshots');
const videoDir = resolve(mediaDir, '_video');
mkdirSync(shotDir, { recursive: true });
mkdirSync(videoDir, { recursive: true });

const settle = async (page, ms = 1200) => {
  await page.waitForLoadState('networkidle').catch(() => {});
  await page.waitForTimeout(ms);
};

const browser = await chromium.launch();
const context = await browser.newContext({
  viewport: { width: 1440, height: 900 },
  deviceScaleFactor: 2, // crisp screenshots
  recordVideo: { dir: videoDir, size: { width: 1440, height: 900 } },
});
const page = await context.newPage();

const shot = async (name) => {
  await settle(page);
  await page.screenshot({ path: resolve(shotDir, `${name}.png`), fullPage: false });
  console.log(`  shot: ${name}.png`);
};

try {
  // 1. Login page
  await page.goto(`${BASE}/login`, { waitUntil: 'domcontentloaded' });
  await shot('01-login');

  // Sign in
  await page.fill('input[name="username"]', USER);
  await page.fill('input[name="password"]', PASS);
  await page.click('button[type="submit"]');
  await page.waitForURL((u) => !u.pathname.startsWith('/login'), { timeout: 15000 }).catch(() => {});
  await shot('02-dashboard');

  // 2. Device list for an environment, then the device detail (port panel).
  const ENV = process.env.NB_ENV ?? 'dc';
  const DEVICE_PATH = process.env.NB_DEVICE_PATH; // e.g. /env/dc/devices/<id>
  await page.goto(`${BASE}/env/${ENV}`, { waitUntil: 'domcontentloaded' }).catch(() => {});
  await shot('03-device-list');
  if (DEVICE_PATH) {
    await page.goto(`${BASE}${DEVICE_PATH}`, { waitUntil: 'domcontentloaded' }).catch(() => {});
    await settle(page, 2500); // let the 3D switch + port grid render
    await shot('04-device-detail');
  }

  // 3. Other routes
  for (const [route, name] of [
    ['/requests', '05-requests'],
    ['/queue', '06-admin-queue'],
    ['/settings', '07-settings'],
    ['/about', '08-about'],
  ]) {
    await page.goto(`${BASE}${route}`, { waitUntil: 'domcontentloaded' }).catch(() => {});
    await shot(name);
  }

  console.log('capture OK');
} finally {
  await context.close(); // flushes the video file
  await browser.close();
}

// Rename the autogenerated video to a stable name.
const vids = readdirSync(videoDir).filter((f) => f.endsWith('.webm'));
if (vids.length) {
  renameSync(resolve(videoDir, vids[0]), resolve(mediaDir, 'northbound-tour.webm'));
  rmSync(videoDir, { recursive: true, force: true });
  console.log('video: docs/media/northbound-tour.webm');
}
