/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Platforms */
        get: operations["list_platforms_api_platforms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials and issue a JWT. 401 (generic) on any mismatch.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Stateless logout: server-side no-op for v1; client discards the token.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Me
         * @description Return the currently authenticated user.
         */
        get: operations["read_me_api_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description List all users (admin only).
         */
        get: operations["list_users_api_users_get"];
        put?: never;
        /**
         * Create User
         * @description Create a user with a hashed password (admin only). 409 on duplicate name.
         */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Connection
         * @description Live credential probe. Does NOT persist anything.
         */
        post: operations["test_connection_api_devices_test_connection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover
         * @description Discovery preview for the wizard. Does NOT persist anything.
         */
        post: operations["discover_api_devices_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Devices
         * @description List devices (optional ``?environment=`` filter). Never returns creds.
         */
        get: operations["list_devices_api_devices_get"];
        put?: never;
        /**
         * Create Device
         * @description Atomic onboard: re-discover, then persist device + ports + backup + audit.
         *
         *     Discovery runs BEFORE the transaction — if it fails, there is no DB hit.
         *     The persist runs inside one ``session.begin()`` block; any failure rolls
         *     the whole unit back, leaving no orphan device or ports.
         */
        post: operations["create_device_api_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device
         * @description Device detail. Never returns creds.
         */
        get: operations["get_device_api_devices__device_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Device
         * @description Offboard a device. port_metadata + backups cascade via FK ondelete.
         */
        delete: operations["delete_device_api_devices__device_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rotate Credentials
         * @description Re-test new creds against the device; only store them if the probe passes.
         *
         *     On a failed probe the stored (old) credentials are left untouched — 400.
         */
        patch: operations["rotate_credentials_api_devices__device_id__credentials_patch"];
        trace?: never;
    };
    "/api/devices/{device_id}/ports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ports
         * @description Live port list (cached 30s). ``?refresh=true`` bypasses the cache.
         */
        get: operations["get_ports_api_devices__device_id__ports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/ports/{port_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Port Detail
         * @description Single-port detail: live state + metadata + recent audit history.
         */
        get: operations["get_port_detail_api_devices__device_id__ports__port_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Port Metadata
         * @description Admin direct edit of port *metadata* (host_model/bmc_ip/notes).
         *
         *     Metadata-only: this writes the DB ``port_metadata`` row, NOT the device, so
         *     ``assert_writable`` is deliberately not invoked. Writes an audit entry and
         *     stamps ``last_human_edit_*``.
         */
        patch: operations["patch_port_metadata_api_devices__device_id__ports__port_name__patch"];
        trace?: never;
    };
    "/api/devices/{device_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Running config (cached). ``?refresh=true`` re-fetches from the device.
         */
        get: operations["get_config_api_devices__device_id__config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/config/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backup Now
         * @description Take a config backup now (admin).
         */
        post: operations["backup_now_api_devices__device_id__config_backup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/config/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Backups
         * @description List a device's config backups, newest first.
         */
        get: operations["list_backups_api_devices__device_id__config_backups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/config/backups/{backup_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backup Diff
         * @description Unified diff of a stored backup vs the current running config.
         */
        get: operations["backup_diff_api_devices__device_id__config_backups__backup_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Requests
         * @description List requests. ``?mine=true`` filters to the caller; ``?request_status=``
         *     filters by state.
         */
        get: operations["list_requests_api_requests_get"];
        put?: never;
        /**
         * Create Request
         * @description File a change request. 403 if the target device is read-only (fail fast).
         */
        post: operations["create_request_api_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Request
         * @description Request detail, including the rendered diff if available.
         */
        get: operations["get_request_api_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Request
         * @description Approve (no apply). pending → approved.
         */
        post: operations["approve_request_api_requests__request_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Request
         * @description Reject with a required comment. pending → rejected.
         */
        post: operations["reject_request_api_requests__request_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Request
         * @description Apply an approved (or pending, approve+apply shortcut) request via the driver.
         */
        post: operations["apply_request_api_requests__request_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Request
         * @description Confirm a commit-confirm apply within its window. awaiting_confirm → applied.
         */
        post: operations["confirm_request_api_requests__request_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit
         * @description Filtered audit list, newest first (``?device_id=&port=&user=``).
         */
        get: operations["list_audit_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuditEntryOut
         * @description A single audit-log row (also reused by the audit router).
         */
        AuditEntryOut: {
            /** Id */
            id: string;
            /** User Id */
            user_id?: string | null;
            /** Action */
            action: string;
            /** Target Device Id */
            target_device_id?: string | null;
            /** Target Port */
            target_port?: string | null;
            /** Before */
            before?: {
                [key: string]: unknown;
            } | null;
            /** After */
            after?: {
                [key: string]: unknown;
            } | null;
            /** Result */
            result: string;
            /** Created At */
            created_at: string;
        };
        /**
         * AuthMethod
         * @enum {string}
         */
        AuthMethod: "password" | "ssh_key" | "api_token" | "snmp_v2c_community" | "snmp_v3";
        /**
         * BackupDiffOut
         * @description Unified diff between a stored backup and the current running config.
         */
        BackupDiffOut: {
            /** Backup Id */
            backup_id: string;
            /** Diff */
            diff: string;
        };
        /**
         * BackupOut
         * @description A stored config backup row.
         */
        BackupOut: {
            /** Id */
            id: string;
            /** Device Id */
            device_id: string;
            /** Fetched At */
            fetched_at: string;
            /** Fetched By */
            fetched_by: string;
        };
        /**
         * ChangeRequestStatus
         * @enum {string}
         */
        ChangeRequestStatus: "pending" | "approved" | "rejected" | "applying" | "awaiting_confirm" | "applied" | "failed" | "reverted";
        /**
         * ConfigOut
         * @description Running config snapshot.
         */
        ConfigOut: {
            /** Config Text */
            config_text: string;
            /** Cached */
            cached: boolean;
        };
        /**
         * ConnectionTestIn
         * @description Body of ``POST /api/devices/test-connection`` — transient, no persist.
         */
        ConnectionTestIn: {
            /** Platform Id */
            platform_id: string;
            /** Mgmt Ip */
            mgmt_ip: string;
            /** Port */
            port?: number | null;
            /**
             * Prefer Native Api
             * @default true
             */
            prefer_native_api: boolean;
            credentials?: components["schemas"]["CredentialsIn"];
        };
        /**
         * CredentialsIn
         * @description Inbound credential bag. All fields optional; the driver interprets
         *     them per its declared ``auth_methods``. Never echoed back in a response.
         */
        CredentialsIn: {
            /** Username */
            username?: string | null;
            /** Password */
            password?: string | null;
            /** Ssh Private Key */
            ssh_private_key?: string | null;
            /** Api Token */
            api_token?: string | null;
            /** Snmp Community */
            snmp_community?: string | null;
        };
        /**
         * CredentialsRotateIn
         * @description Body of ``PATCH /api/devices/{id}/credentials``.
         */
        CredentialsRotateIn: {
            credentials: components["schemas"]["CredentialsIn"];
        };
        /**
         * DeviceCreateIn
         * @description Body of ``POST /api/devices`` — atomic onboard.
         */
        DeviceCreateIn: {
            /** Name */
            name: string;
            environment: components["schemas"]["Environment"];
            role: components["schemas"]["DeviceRole"];
            /** Platform Id */
            platform_id: string;
            /** Mgmt Ip */
            mgmt_ip: string;
            /** Port */
            port?: number | null;
            /** Ssh User */
            ssh_user?: string | null;
            /**
             * Prefer Native Api
             * @default true
             */
            prefer_native_api: boolean;
            credentials?: components["schemas"]["CredentialsIn"];
        };
        /**
         * DeviceOut
         * @description Public view of a device. NEVER includes credentials of any kind.
         */
        DeviceOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            environment: components["schemas"]["Environment"];
            role: components["schemas"]["DeviceRole"];
            /** Platform */
            platform: string;
            /** Mgmt Ip */
            mgmt_ip: string;
            /** Ssh User */
            ssh_user?: string | null;
            /** Prefer Native Api */
            prefer_native_api: boolean;
            capabilities?: components["schemas"]["DriverCapabilities"] | null;
            /**
             * Writable
             * @default false
             */
            writable: boolean;
            /** Reachable */
            reachable?: boolean | null;
        };
        /**
         * DeviceRole
         * @enum {string}
         */
        DeviceRole: "leaf" | "spine" | "router" | "vpn";
        /**
         * DiscoverIn
         * @description Body of ``POST /api/devices/discover`` — same shape as test-connection.
         */
        DiscoverIn: {
            /** Platform Id */
            platform_id: string;
            /** Mgmt Ip */
            mgmt_ip: string;
            /** Port */
            port?: number | null;
            /**
             * Prefer Native Api
             * @default true
             */
            prefer_native_api: boolean;
            credentials?: components["schemas"]["CredentialsIn"];
        };
        /**
         * DiscoverOut
         * @description Onboarding preview — never persisted.
         */
        DiscoverOut: {
            /** Hostname */
            hostname: string;
            /** Ports */
            ports?: components["schemas"]["PortOut"][];
            /**
             * Running Config
             * @default
             */
            running_config: string;
            /** Services */
            services?: {
                [key: string]: boolean;
            };
        };
        /**
         * DriverCapabilities
         * @description What a driver can and cannot do. Surfaced to the UI verbatim.
         */
        DriverCapabilities: {
            /** Writable */
            writable: boolean;
            /** Supports Commit Confirm */
            supports_commit_confirm: boolean;
            /** Native Api Available */
            native_api_available: boolean;
            /** Supports Snmp Read */
            supports_snmp_read: boolean;
            /** Supports Lldp */
            supports_lldp: boolean;
            /** Max Concurrency */
            max_concurrency: number;
            /** Auth Methods */
            auth_methods: components["schemas"]["AuthMethod"][];
            /** Web Ui Url Template */
            web_ui_url_template?: string | null;
        };
        /**
         * Environment
         * @enum {string}
         */
        Environment: "lab" | "dc";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * LoginRequest
         * @description Body of ``POST /api/auth/login``.
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description Successful login result. ``token_type`` is always ``bearer``.
         */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            role: components["schemas"]["UserRole"];
            /** Username */
            username: string;
        };
        /** PlatformInfo */
        PlatformInfo: {
            /** Platform Id */
            platform_id: string;
            /** Display Name */
            display_name: string;
            capabilities: components["schemas"]["DriverCapabilities"];
        };
        /**
         * PortChange
         * @description User-facing change request payload.
         */
        PortChange: {
            /** Untagged Vlan */
            untagged_vlan?: number | null;
            /** Tagged Vlans */
            tagged_vlans?: number[] | null;
            /** Host Model */
            host_model?: string | null;
            /** Bmc Ip */
            bmc_ip?: string | null;
            /** Notes */
            notes?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * PortDetailOut
         * @description Single-port detail: live state + metadata + recent audit history.
         */
        PortDetailOut: {
            port: components["schemas"]["PortStateOut"];
            /** History */
            history?: components["schemas"]["AuditEntryOut"][];
        };
        /**
         * PortMetadataPatchIn
         * @description Admin direct edit of port metadata (DB-only; no device write).
         */
        PortMetadataPatchIn: {
            /** Host Model */
            host_model?: string | null;
            /** Bmc Ip */
            bmc_ip?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * PortOut
         * @description A discovered port, with parsed human fields surfaced for preview.
         */
        PortOut: {
            /** Name */
            name: string;
            /** Admin Up */
            admin_up: boolean;
            /** Link Up */
            link_up: boolean;
            /** Speed Mbps */
            speed_mbps?: number | null;
            /** Duplex */
            duplex?: string | null;
            /** Mac */
            mac?: string | null;
            /** Mtu */
            mtu?: number | null;
            /** Untagged Vlan */
            untagged_vlan?: number | null;
            /** Tagged Vlans */
            tagged_vlans?: number[];
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Host Model
             * @default
             */
            host_model: string;
            /**
             * Bmc Ip
             * @default
             */
            bmc_ip: string;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /**
         * PortStateOut
         * @description A live port plus its human-authored metadata.
         */
        PortStateOut: {
            /** Name */
            name: string;
            /** Admin Up */
            admin_up: boolean;
            /** Link Up */
            link_up: boolean;
            /** Speed Mbps */
            speed_mbps?: number | null;
            /** Duplex */
            duplex?: string | null;
            /** Mac */
            mac?: string | null;
            /** Mtu */
            mtu?: number | null;
            /** Untagged Vlan */
            untagged_vlan?: number | null;
            /** Tagged Vlans */
            tagged_vlans?: number[];
            /**
             * Description
             * @default
             */
            description: string;
            /** Services */
            services?: {
                [key: string]: boolean;
            };
            /**
             * Host Model
             * @default
             */
            host_model: string;
            /**
             * Bmc Ip
             * @default
             */
            bmc_ip: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Last Human Edit At */
            last_human_edit_at?: string | null;
            /** Last Human Edit By */
            last_human_edit_by?: string | null;
        };
        /**
         * RequestCreateIn
         * @description Body of ``POST /api/requests`` — file a change request.
         */
        RequestCreateIn: {
            /** Device Id */
            device_id: string;
            /** Port Name */
            port_name: string;
            requested_changes: components["schemas"]["PortChange"];
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /**
         * RequestOut
         * @description Public view of a change request.
         */
        RequestOut: {
            /** Id */
            id: string;
            /** Device Id */
            device_id: string;
            /** Port Name */
            port_name: string;
            /** Requested By */
            requested_by: string;
            /** Requested Changes */
            requested_changes: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string;
            status: components["schemas"]["ChangeRequestStatus"];
            /** Reviewer Id */
            reviewer_id?: string | null;
            /** Reviewer Comment */
            reviewer_comment?: string | null;
            /** Diff Text */
            diff_text?: string | null;
            /** Confirm Token */
            confirm_token?: string | null;
            /** Confirm Deadline At */
            confirm_deadline_at?: number | null;
            /** Created At */
            created_at: string;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Applied At */
            applied_at?: string | null;
        };
        /**
         * RequestRejectIn
         * @description Body of ``POST /api/requests/{id}/reject`` — comment required.
         */
        RequestRejectIn: {
            /** Comment */
            comment: string;
        };
        /**
         * TestConnectionOut
         * @description Result of a live credential probe. Mirrors the driver TestResult.
         */
        TestConnectionOut: {
            /** Ok */
            ok: boolean;
            /** Latency Ms */
            latency_ms: number;
            /** Platform Version */
            platform_version?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * UserCreate
         * @description Body of ``POST /api/users`` (admin only).
         */
        UserCreate: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            role: components["schemas"]["UserRole"];
            /** Email */
            email?: string | null;
        };
        /**
         * UserOut
         * @description Public view of a user. NEVER includes ``password_hash``.
         */
        UserOut: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            role: components["schemas"]["UserRole"];
            /** Email */
            email?: string | null;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "requester";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_platforms_api_platforms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformInfo"][];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_me_api_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connection_api_devices_test_connection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionTestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_api_devices_discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_devices_get: {
        parameters: {
            query?: {
                environment?: components["schemas"]["Environment"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_device_api_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_api_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_device_api_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_credentials_api_devices__device_id__credentials_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRotateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ports_api_devices__device_id__ports_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortStateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_port_detail_api_devices__device_id__ports__port_name__get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                device_id: string;
                port_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_port_metadata_api_devices__device_id__ports__port_name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
                port_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortMetadataPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_devices__device_id__config_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backup_now_api_devices__device_id__config_backup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backups_api_devices__device_id__config_backups_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backup_diff_api_devices__device_id__config_backups__backup_id__diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
                backup_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupDiffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_api_requests_get: {
        parameters: {
            query?: {
                mine?: boolean;
                request_status?: components["schemas"]["ChangeRequestStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_api_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_api_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_request_api_requests__request_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_request_api_requests__request_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestRejectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_request_api_requests__request_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_request_api_requests__request_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_audit_get: {
        parameters: {
            query?: {
                device_id?: string | null;
                port?: string | null;
                user?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
