/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit
         * @description Filtered audit list, newest first (``?device_id=&port=&user=``).
         */
        get: operations["list_audit_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials, set session cookies, and return the login body.
         *
         *     401 (generic) on any mismatch.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the session cookies. (Tokens are stateless, so this is the session
         *     end for cookie clients; Bearer clients simply drop their token.)
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate the session from the refresh cookie: issue a new access + refresh
         *     pair (rotation) and re-set both cookies. 401 if the refresh cookie is
         *     missing/invalid/expired or the user is gone.
         */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Public self-registration. Always creates a REQUESTER and auto-logs in.
         *
         *     The role is forced — the client cannot escalate to admin here (only
         *     ``POST /api/users`` can, and that is admin-gated). 403 when open
         *     registration is disabled; 409 on a duplicate username; throttled per
         *     (ip, username) like login. Returns a JWT so the UI logs in immediately.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Devices
         * @description List devices (optional ``?environment=<site slug>`` filter). Never returns creds.
         */
        get: operations["list_devices_api_devices_get"];
        put?: never;
        /**
         * Create Device
         * @description Atomic onboard: re-discover, then persist device + ports + backup + audit.
         *
         *     Discovery runs BEFORE the transaction — if it fails, there is no DB hit.
         *     The persist runs inside one ``session.begin()`` block; any failure rolls
         *     the whole unit back, leaving no orphan device or ports.
         */
        post: operations["create_device_api_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover
         * @description Discovery preview for the wizard. Does NOT persist anything.
         */
        post: operations["discover_api_devices_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Connection
         * @description Live credential probe. Does NOT persist anything.
         */
        post: operations["test_connection_api_devices_test_connection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device
         * @description Device detail. Never returns creds.
         */
        get: operations["get_device_api_devices__device_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Device
         * @description Offboard a device.
         *
         *     port_metadata + backups cascade via FK ondelete=CASCADE (operational data).
         *     Change-request history uses FK ondelete=RESTRICT, so a device that has any
         *     change requests CANNOT be hard-deleted — the compliance trail must be
         *     retained. That case surfaces as 409 Conflict rather than an unhandled 500.
         */
        delete: operations["delete_device_api_devices__device_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Running config (cached). ``?refresh=true`` re-fetches from the device.
         */
        get: operations["get_config_api_devices__device_id__config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/config/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backup Now
         * @description Take a config backup now (admin).
         */
        post: operations["backup_now_api_devices__device_id__config_backup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/config/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Backups
         * @description List a device's config backups, newest first.
         */
        get: operations["list_backups_api_devices__device_id__config_backups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/config/backups/{backup_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backup Diff
         * @description Unified diff of a stored backup vs the current running config.
         */
        get: operations["backup_diff_api_devices__device_id__config_backups__backup_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rotate Credentials
         * @description Re-test new creds against the device; only store them if the probe passes.
         *
         *     On a failed probe the stored (old) credentials are left untouched — 400.
         */
        patch: operations["rotate_credentials_api_devices__device_id__credentials_patch"];
        trace?: never;
    };
    "/api/devices/{device_id}/l3-interfaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get L3 Interfaces
         * @description Addressed/non-switchport interfaces: management port, L3 VLAN SVIs, LAGs.
         */
        get: operations["get_l3_interfaces_api_devices__device_id__l3_interfaces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/ports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ports
         * @description Live port list (cached 30s). ``?refresh=true`` bypasses the cache.
         */
        get: operations["get_ports_api_devices__device_id__ports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/ports/{port_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Port Detail
         * @description Single-port detail: live state + metadata + recent audit history.
         */
        get: operations["get_port_detail_api_devices__device_id__ports__port_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Port Metadata
         * @description Admin direct edit of port *metadata* (host_model/bmc_ip/notes).
         *
         *     Metadata-only: this writes the DB ``port_metadata`` row, NOT the device, so
         *     ``assert_writable`` is deliberately not invoked. Writes an audit entry and
         *     stamps ``last_human_edit_*``.
         */
        patch: operations["patch_port_metadata_api_devices__device_id__ports__port_name__patch"];
        trace?: never;
    };
    "/api/devices/{device_id}/ports/{port_name}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Port Config
         * @description Admin-only DIRECT write of device port tunables.
         *
         *     Covers port-mode (access/trunk), native/untagged VLAN, tagged VLANs, MTU and
         *     admin enable/disable. Declared BEFORE the metadata ``:path`` route. Immediate
         *     commit, no approval gate; 403 for non-admin, 422 if no field is set.
         */
        patch: operations["set_port_config_api_devices__device_id__ports__port_name__config_patch"];
        trace?: never;
    };
    "/api/devices/{device_id}/ports/{port_name}/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Port Description
         * @description Admin-only DIRECT write of the on-device port description.
         *
         *     Declared BEFORE the metadata ``:path`` route so ``…/description`` matches
         *     here, not as a port named ``…/description``.
         */
        patch: operations["set_port_description_api_devices__device_id__ports__port_name__description_patch"];
        trace?: never;
    };
    "/api/devices/{device_id}/protocols/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Protocol Detail
         * @description Operational detail (named tables) for one protocol — e.g. OSPF neighbors
         *     + link-state database. Parsed from device CLI gets via TextFSM.
         */
        get: operations["get_protocol_detail_api_devices__device_id__protocols__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/rediscover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rediscover
         * @description Re-probe an onboarded device and refresh its stored snapshot.
         *
         *     Non-destructive: adds metadata rows only for ports seen for the first time
         *     (human edits preserved) and writes a fresh baseline backup. 502 on a probe
         *     failure. Invalidates the live port-state cache so the next read is fresh.
         */
        post: operations["rediscover_api_devices__device_id__rediscover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Info
         * @description Live system snapshot: control-plane protocols, mgmt services, MAC table.
         *
         *     Sections a driver can't reach come back empty (``mac_supported=false``
         *     distinguishes an unreadable MAC table from a genuinely empty one).
         */
        get: operations["get_system_info_api_devices__device_id__system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/vlans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vlans
         * @description The device's VLAN database: id, name, description, L3 SVI, member-port
         *     count. Backs the VLANs view and the request VLAN picker.
         */
        get: operations["get_vlans_api_devices__device_id__vlans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_id}/writes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Device Writes
         * @description Enable/disable config writes for a device (gradual rollout / kill-switch).
         *
         *     Does NOT override intrinsic read-only status (router/vpn role or a
         *     non-writable platform) — ``writable`` in the response reflects the combined
         *     policy. Audited.
         */
        patch: operations["set_device_writes_api_devices__device_id__writes_patch"];
        trace?: never;
    };
    "/api/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Platforms */
        get: operations["list_platforms_api_platforms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Requests
         * @description List requests.
         *
         *     Non-admin callers ALWAYS see only their own requests — the client ``?mine``
         *     flag is ignored for them so it cannot be used to enumerate others' requests.
         *     Admins see every request and may narrow with ``?mine`` / ``?request_status``.
         */
        get: operations["list_requests_api_requests_get"];
        put?: never;
        /**
         * Create Request
         * @description File a change request. 403 if the target device is read-only (fail fast).
         */
        post: operations["create_request_api_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Request
         * @description Request detail, including the rendered diff if available.
         *
         *     Non-admin callers may only read their own request; a foreign id returns 404
         *     (object-level authz — see :func:`_assert_can_read`).
         */
        get: operations["get_request_api_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Request
         * @description Apply an approved (or pending, approve+apply shortcut) request via the driver.
         */
        post: operations["apply_request_api_requests__request_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Request
         * @description Approve (no apply). pending → approved.
         */
        post: operations["approve_request_api_requests__request_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Request
         * @description Confirm a commit-confirm apply within its window. awaiting_confirm → applied.
         */
        post: operations["confirm_request_api_requests__request_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Request
         * @description Reject with a required comment. pending → rejected.
         */
        post: operations["reject_request_api_requests__request_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Runtime Settings
         * @description Return the current admin-tunable settings.
         */
        get: operations["get_runtime_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Runtime Settings
         * @description Update runtime settings (admin). 422 on an invalid rate-limit string.
         */
        patch: operations["update_runtime_settings_api_settings_patch"];
        trace?: never;
    };
    "/api/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sites
         * @description List every site in the catalog, with live device counts.
         */
        get: operations["list_sites_api_sites_get"];
        put?: never;
        /**
         * Create Site
         * @description Create a new site (admin only). Slug must be unique.
         */
        post: operations["create_site_api_sites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Site
         * @description Delete a site (admin only). Blocked if any device is still assigned.
         */
        delete: operations["delete_site_api_sites__site_id__delete"];
        options?: never;
        head?: never;
        /**
         * Rename Site
         * @description Rename a site (admin only). The slug is immutable to keep URLs stable.
         */
        patch: operations["rename_site_api_sites__site_id__patch"];
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description List all users (admin only).
         */
        get: operations["list_users_api_users_get"];
        put?: never;
        /**
         * Create User
         * @description Create a user with a hashed password (admin only). 409 on duplicate name.
         */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Me
         * @description Return the currently authenticated user.
         */
        get: operations["read_me_api_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuditEntryOut
         * @description A single audit-log row (also reused by the audit router).
         */
        AuditEntryOut: {
            /** Action */
            action: string;
            /** After */
            after?: {
                [key: string]: unknown;
            } | null;
            /** Before */
            before?: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Result */
            result: string;
            /** Target Device Id */
            target_device_id?: string | null;
            /** Target Port */
            target_port?: string | null;
            /** User Id */
            user_id?: string | null;
        };
        /**
         * AuthMethod
         * @enum {string}
         */
        AuthMethod: "password" | "ssh_key" | "api_token" | "snmp_v2c_community" | "snmp_v3";
        /**
         * BackupDiffOut
         * @description Unified diff between a stored backup and the current running config.
         */
        BackupDiffOut: {
            /** Backup Id */
            backup_id: string;
            /** Diff */
            diff: string;
        };
        /**
         * BackupOut
         * @description A stored config backup row.
         */
        BackupOut: {
            /** Device Id */
            device_id: string;
            /** Fetched At */
            fetched_at: string;
            /** Fetched By */
            fetched_by: string;
            /** Id */
            id: string;
        };
        /**
         * ChangeRequestStatus
         * @enum {string}
         */
        ChangeRequestStatus: "pending" | "approved" | "rejected" | "applying" | "awaiting_confirm" | "applied" | "failed" | "reverted";
        /**
         * ConfigOut
         * @description Running config snapshot.
         */
        ConfigOut: {
            /** Cached */
            cached: boolean;
            /** Config Text */
            config_text: string;
        };
        /**
         * ConnectionTestIn
         * @description Body of ``POST /api/devices/test-connection`` — transient, no persist.
         */
        ConnectionTestIn: {
            credentials?: components["schemas"]["CredentialsIn"];
            /** Mgmt Ip */
            mgmt_ip: string;
            /** Platform Id */
            platform_id: string;
            /** Port */
            port?: number | null;
            /**
             * Prefer Native Api
             * @default true
             */
            prefer_native_api: boolean;
        };
        /**
         * CredentialsIn
         * @description Inbound credential bag. All fields optional; the driver interprets
         *     them per its declared ``auth_methods``. Never echoed back in a response.
         */
        CredentialsIn: {
            /** Api Token */
            api_token?: string | null;
            /** Enable Secret */
            enable_secret?: string | null;
            /** Password */
            password?: string | null;
            /** Snmp Community */
            snmp_community?: string | null;
            /** Ssh Private Key */
            ssh_private_key?: string | null;
            /** Username */
            username?: string | null;
        };
        /**
         * CredentialsRotateIn
         * @description Body of ``PATCH /api/devices/{id}/credentials``.
         */
        CredentialsRotateIn: {
            credentials: components["schemas"]["CredentialsIn"];
        };
        /**
         * DeviceCreateIn
         * @description Body of ``POST /api/devices`` — atomic onboard.
         */
        DeviceCreateIn: {
            credentials?: components["schemas"]["CredentialsIn"];
            /** Environment */
            environment: string;
            /** Mgmt Ip */
            mgmt_ip: string;
            /** Name */
            name: string;
            /** Platform Id */
            platform_id: string;
            /** Port */
            port?: number | null;
            /**
             * Prefer Native Api
             * @default true
             */
            prefer_native_api: boolean;
            role: components["schemas"]["DeviceRole"];
            /** Ssh User */
            ssh_user?: string | null;
        };
        /** DeviceFactsOut */
        DeviceFactsOut: {
            /**
             * Base Mac
             * @default
             */
            base_mac: string;
            /**
             * License
             * @default
             */
            license: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Os Version
             * @default
             */
            os_version: string;
            /**
             * Released
             * @default
             */
            released: string;
            /**
             * Serial
             * @default
             */
            serial: string;
            /**
             * Uptime
             * @default
             */
            uptime: string;
        };
        /**
         * DeviceOut
         * @description Public view of a device. NEVER includes credentials of any kind.
         */
        DeviceOut: {
            capabilities?: components["schemas"]["DriverCapabilities"] | null;
            /** Environment */
            environment: string;
            /** Id */
            id: string;
            /** Mgmt Ip */
            mgmt_ip: string;
            /** Name */
            name: string;
            /** Platform */
            platform: string;
            /** Prefer Native Api */
            prefer_native_api: boolean;
            /** Reachable */
            reachable?: boolean | null;
            role: components["schemas"]["DeviceRole"];
            /** Ssh User */
            ssh_user?: string | null;
            /**
             * Writable
             * @default false
             */
            writable: boolean;
            /**
             * Writes Enabled
             * @default true
             */
            writes_enabled: boolean;
        };
        /**
         * DeviceRole
         * @enum {string}
         */
        DeviceRole: "leaf" | "spine" | "router" | "vpn";
        /**
         * DeviceWritesIn
         * @description Body of ``PATCH /api/devices/{id}/writes`` — the per-device write flag.
         */
        DeviceWritesIn: {
            /** Enabled */
            enabled: boolean;
        };
        /**
         * DiscoverIn
         * @description Body of ``POST /api/devices/discover`` — same shape as test-connection.
         */
        DiscoverIn: {
            credentials?: components["schemas"]["CredentialsIn"];
            /** Mgmt Ip */
            mgmt_ip: string;
            /** Platform Id */
            platform_id: string;
            /** Port */
            port?: number | null;
            /**
             * Prefer Native Api
             * @default true
             */
            prefer_native_api: boolean;
        };
        /**
         * DiscoverOut
         * @description Onboarding preview — never persisted.
         */
        DiscoverOut: {
            /** Hostname */
            hostname: string;
            /** Ports */
            ports?: components["schemas"]["PortOut"][];
            /**
             * Running Config
             * @default
             */
            running_config: string;
            /** Services */
            services?: {
                [key: string]: boolean;
            };
        };
        /**
         * DriverCapabilities
         * @description What a driver can and cannot do. Surfaced to the UI verbatim.
         */
        DriverCapabilities: {
            /** Auth Methods */
            auth_methods: components["schemas"]["AuthMethod"][];
            /** Max Concurrency */
            max_concurrency: number;
            /** Native Api Available */
            native_api_available: boolean;
            /** Supports Commit Confirm */
            supports_commit_confirm: boolean;
            /** Supports Lldp */
            supports_lldp: boolean;
            /** Supports Snmp Read */
            supports_snmp_read: boolean;
            /** Web Ui Url Template */
            web_ui_url_template?: string | null;
            /** Writable */
            writable: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** L3InterfaceOut */
        L3InterfaceOut: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Gateway
             * @default
             */
            gateway: string;
            /**
             * Ipv4
             * @default
             */
            ipv4: string;
            /** Kind */
            kind: string;
            /** Mtu */
            mtu?: number | null;
            /** Name */
            name: string;
        };
        /**
         * LoginRequest
         * @description Body of ``POST /api/auth/login``.
         */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * LoginResponse
         * @description Successful login result. ``token_type`` is always ``bearer``.
         */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            role: components["schemas"]["UserRole"];
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Username */
            username: string;
        };
        /** MacEntryOut */
        MacEntryOut: {
            /** Age */
            age?: string | null;
            /** Interface */
            interface: string;
            /** Mac */
            mac: string;
            /** Type */
            type: string;
            /** Vlan */
            vlan?: number | null;
        };
        /** MgmtServiceOut */
        MgmtServiceOut: {
            /**
             * Configured
             * @default true
             */
            configured: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Enabled */
            enabled: boolean;
            /** Name */
            name: string;
            /** Port */
            port?: number | null;
        };
        /** PlatformInfo */
        PlatformInfo: {
            capabilities: components["schemas"]["DriverCapabilities"];
            /** Display Name */
            display_name: string;
            /** Platform Id */
            platform_id: string;
        };
        /**
         * PortChange
         * @description User-facing change request payload.
         *
         *     VLAN IDs are validated against the 802.1Q valid range 1..4094; 0 and 4095
         *     are reserved and rejected at this system boundary.
         */
        PortChange: {
            /** Bmc Ip */
            bmc_ip?: string | null;
            /** Description */
            description?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Host Model */
            host_model?: string | null;
            /** Mtu */
            mtu?: number | null;
            /** Notes */
            notes?: string | null;
            /** Port Mode */
            port_mode?: ("access" | "trunk") | null;
            /** Tagged Vlans */
            tagged_vlans?: number[] | null;
            /** Untagged Vlan */
            untagged_vlan?: number | null;
        };
        /**
         * PortConfigIn
         * @description Admin direct edit of on-device port tunables (config write).
         *
         *     All fields optional; at least one must be set. VLAN IDs follow 802.1Q
         *     (1..4094). ``enabled`` maps to the device's admin shut/no-shut.
         */
        PortConfigIn: {
            /** Enabled */
            enabled?: boolean | null;
            /** Mtu */
            mtu?: number | null;
            /** Port Mode */
            port_mode?: ("access" | "trunk") | null;
            /** Tagged Vlans */
            tagged_vlans?: number[] | null;
            /** Untagged Vlan */
            untagged_vlan?: number | null;
        };
        /**
         * PortDescriptionIn
         * @description Admin direct edit of the port's on-device description (config write).
         */
        PortDescriptionIn: {
            /** Description */
            description: string;
        };
        /**
         * PortDetailOut
         * @description Single-port detail: live state + metadata + recent audit history.
         */
        PortDetailOut: {
            /** History */
            history?: components["schemas"]["AuditEntryOut"][];
            port: components["schemas"]["PortStateOut"];
        };
        /**
         * PortMetadataPatchIn
         * @description Admin direct edit of port metadata (DB-only; no device write).
         */
        PortMetadataPatchIn: {
            /** Bmc Ip */
            bmc_ip?: string | null;
            /** Host Model */
            host_model?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * PortOut
         * @description A discovered port, with parsed human fields surfaced for preview.
         */
        PortOut: {
            /** Admin Up */
            admin_up: boolean;
            /**
             * Bmc Ip
             * @default
             */
            bmc_ip: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Duplex */
            duplex?: string | null;
            /**
             * Host Model
             * @default
             */
            host_model: string;
            /** Link Up */
            link_up: boolean;
            /** Mac */
            mac?: string | null;
            /** Mtu */
            mtu?: number | null;
            /** Name */
            name: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Speed Mbps */
            speed_mbps?: number | null;
            /** Tagged Vlans */
            tagged_vlans?: number[];
            /** Untagged Vlan */
            untagged_vlan?: number | null;
        };
        /**
         * PortStateOut
         * @description A live port plus its human-authored metadata.
         */
        PortStateOut: {
            /** Admin Up */
            admin_up: boolean;
            /**
             * Bmc Ip
             * @default
             */
            bmc_ip: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Duplex */
            duplex?: string | null;
            /**
             * Host Model
             * @default
             */
            host_model: string;
            /** Last Human Edit At */
            last_human_edit_at?: string | null;
            /** Last Human Edit By */
            last_human_edit_by?: string | null;
            /** Link Up */
            link_up: boolean;
            /** Mac */
            mac?: string | null;
            /** Mtu */
            mtu?: number | null;
            /** Name */
            name: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Services */
            services?: {
                [key: string]: boolean;
            };
            /** Speed Mbps */
            speed_mbps?: number | null;
            /** Tagged Vlans */
            tagged_vlans?: number[];
            /** Untagged Vlan */
            untagged_vlan?: number | null;
        };
        /**
         * ProtocolDetailOut
         * @description Operational detail for one protocol — named tables from CLI gets.
         */
        ProtocolDetailOut: {
            /** Error */
            error?: string | null;
            /** Slug */
            slug: string;
            /** Tables */
            tables?: components["schemas"]["ProtocolTableOut"][];
        };
        /** ProtocolStatusOut */
        ProtocolStatusOut: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Has Detail
             * @default false
             */
            has_detail: boolean;
            /** Name */
            name: string;
            /** Params */
            params?: [
                string,
                string
            ][];
        };
        /** ProtocolTableOut */
        ProtocolTableOut: {
            /** Columns */
            columns?: string[];
            /** Rows */
            rows?: string[][];
            /** Title */
            title: string;
        };
        /**
         * RediscoverOut
         * @description Result of ``POST /api/devices/{id}/rediscover``.
         */
        RediscoverOut: {
            /**
             * Hostname
             * @default
             */
            hostname: string;
            /** Ports Added */
            ports_added: number;
            /** Ports Total */
            ports_total: number;
        };
        /**
         * RegisterRequest
         * @description Body of ``POST /api/auth/register`` (public self-registration).
         *
         *     The role is intentionally absent — self-registered accounts are always
         *     REQUESTER; only an admin can mint privileged users via ``POST /api/users``.
         *     A longer password floor than login applies because this creates the secret.
         */
        RegisterRequest: {
            /** Email */
            email?: string | null;
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * RequestCreateIn
         * @description Body of ``POST /api/requests`` — file a change request.
         */
        RequestCreateIn: {
            /** Device Id */
            device_id: string;
            /** Port Name */
            port_name: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            requested_changes: components["schemas"]["PortChange"];
        };
        /**
         * RequestOut
         * @description Public view of a change request.
         */
        RequestOut: {
            /** Applied At */
            applied_at?: string | null;
            /**
             * Awaiting Confirm
             * @default false
             */
            awaiting_confirm: boolean;
            /** Confirm Deadline At */
            confirm_deadline_at?: number | null;
            /** Created At */
            created_at: string;
            /** Device Id */
            device_id: string;
            /** Diff Text */
            diff_text?: string | null;
            /** Id */
            id: string;
            /** Port Name */
            port_name: string;
            /** Reason */
            reason: string;
            /** Requested By */
            requested_by: string;
            /** Requested Changes */
            requested_changes: {
                [key: string]: unknown;
            };
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Reviewer Comment */
            reviewer_comment?: string | null;
            /** Reviewer Id */
            reviewer_id?: string | null;
            status: components["schemas"]["ChangeRequestStatus"];
        };
        /**
         * RequestRejectIn
         * @description Body of ``POST /api/requests/{id}/reject`` — comment required.
         */
        RequestRejectIn: {
            /** Comment */
            comment: string;
        };
        /**
         * SettingsOut
         * @description Current admin-tunable runtime settings.
         */
        SettingsOut: {
            /**
             * Write Rate Limit
             * @description Write-endpoint rate limit as a slowapi/limits string, e.g. '30/minute'.
             */
            write_rate_limit: string;
        };
        /**
         * SettingsPatch
         * @description Partial update of runtime settings. Only set fields are applied.
         */
        SettingsPatch: {
            /** Write Rate Limit */
            write_rate_limit?: string | null;
        };
        /**
         * SiteCreateIn
         * @description Body of ``POST /api/sites`` (admin only).
         */
        SiteCreateIn: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * SiteOut
         * @description Public view of a site, with a live device count for the picker.
         */
        SiteOut: {
            /**
             * Device Count
             * @default 0
             */
            device_count: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * SiteUpdateIn
         * @description Body of ``PATCH /api/sites/{id}`` — rename only (slug is immutable).
         */
        SiteUpdateIn: {
            /** Name */
            name: string;
        };
        /**
         * SystemInfoOut
         * @description Live system snapshot: device facts, protocols, mgmt services, MAC table.
         */
        SystemInfoOut: {
            facts?: components["schemas"]["DeviceFactsOut"];
            /**
             * Mac Supported
             * @default false
             */
            mac_supported: boolean;
            /** Mac Table */
            mac_table?: components["schemas"]["MacEntryOut"][];
            /** Protocols */
            protocols?: components["schemas"]["ProtocolStatusOut"][];
            /** Services */
            services?: components["schemas"]["MgmtServiceOut"][];
        };
        /**
         * TestConnectionOut
         * @description Result of a live credential probe. Mirrors the driver TestResult.
         */
        TestConnectionOut: {
            /** Error */
            error?: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Ok */
            ok: boolean;
            /** Platform Version */
            platform_version?: string | null;
        };
        /**
         * UserCreate
         * @description Body of ``POST /api/users`` (admin only).
         */
        UserCreate: {
            /** Email */
            email?: string | null;
            /** Password */
            password: string;
            role: components["schemas"]["UserRole"];
            /** Username */
            username: string;
        };
        /**
         * UserOut
         * @description Public view of a user. NEVER includes ``password_hash``.
         */
        UserOut: {
            /** Email */
            email?: string | null;
            /** Id */
            id: string;
            role: components["schemas"]["UserRole"];
            /** Username */
            username: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "requester";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VlanInfoOut */
        VlanInfoOut: {
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * L3 Interface
             * @default
             */
            l3_interface: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Port Count
             * @default 0
             */
            port_count: number;
            /** Vlan Id */
            vlan_id: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_api_audit_get: {
        parameters: {
            query?: {
                device_id?: string | null;
                port?: string | null;
                user?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_devices_get: {
        parameters: {
            query?: {
                environment?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_device_api_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_api_devices_discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connection_api_devices_test_connection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionTestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_api_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_device_api_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_devices__device_id__config_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backup_now_api_devices__device_id__config_backup_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backups_api_devices__device_id__config_backups_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backup_diff_api_devices__device_id__config_backups__backup_id__diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
                backup_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupDiffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_credentials_api_devices__device_id__credentials_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRotateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_l3_interfaces_api_devices__device_id__l3_interfaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["L3InterfaceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ports_api_devices__device_id__ports_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortStateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_port_detail_api_devices__device_id__ports__port_name__get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                device_id: string;
                port_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_port_metadata_api_devices__device_id__ports__port_name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
                port_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortMetadataPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_port_config_api_devices__device_id__ports__port_name__config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
                port_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_port_description_api_devices__device_id__ports__port_name__description_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
                port_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortDescriptionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_protocol_detail_api_devices__device_id__protocols__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtocolDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rediscover_api_devices__device_id__rediscover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RediscoverOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_info_api_devices__device_id__system_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vlans_api_devices__device_id__vlans_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VlanInfoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_device_writes_api_devices__device_id__writes_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceWritesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_platforms_api_platforms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformInfo"][];
                };
            };
        };
    };
    list_requests_api_requests_get: {
        parameters: {
            query?: {
                mine?: boolean;
                request_status?: components["schemas"]["ChangeRequestStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_api_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_api_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_request_api_requests__request_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_request_api_requests__request_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_request_api_requests__request_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_request_api_requests__request_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestRejectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runtime_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_runtime_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sites_api_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"][];
                };
            };
        };
    };
    create_site_api_sites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_site_api_sites__site_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_site_api_sites__site_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_api_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
