"""initial schema

Revision ID: 04844e5d9aae
Revises: 
Create Date: 2026-05-30 17:36:30.979172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04844e5d9aae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('environment', sa.Enum('lab', 'dc', name='environment'), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('leaf', 'spine', 'router', 'vpn', name='device_role'), nullable=False),
    sa.Column('mgmt_ip', sa.String(length=64), nullable=False),
    sa.Column('ssh_user', sa.String(length=128), nullable=True),
    sa.Column('prefer_native_api', sa.Boolean(), nullable=False),
    sa.Column('encrypted_credentials', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('admin', 'requester', name='user_role'), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_device_id', sa.String(length=36), nullable=True),
    sa.Column('target_port', sa.String(length=128), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('port_name', sa.String(length=128), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('requested_changes', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'applying', 'awaiting_confirm', 'applied', 'failed', 'reverted', name='change_request_status'), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('device_state_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('confirm_token', sa.String(length=128), nullable=True),
    sa.Column('confirm_deadline_at', sa.Float(), nullable=True),
    sa.Column('diff_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_backups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('config_text', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_by', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_backups', schema=None) as batch_op:
        batch_op.create_index('ix_config_backups_device_fetched', ['device_id', 'fetched_at'], unique=False)

    op.create_table('port_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('port_name', sa.String(length=128), nullable=False),
    sa.Column('host_model', sa.String(length=256), nullable=False),
    sa.Column('bmc_ip', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('last_human_edit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_human_edit_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'port_name', name='uq_port_metadata_device_port')
    )
    op.create_table('change_request_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=64), nullable=False),
    sa.Column('to_status', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_request_events')
    op.drop_table('port_metadata')
    with op.batch_alter_table('config_backups', schema=None) as batch_op:
        batch_op.drop_index('ix_config_backups_device_fetched')

    op.drop_table('config_backups')
    op.drop_table('change_requests')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('devices')
    # ### end Alembic commands ###
