"""add device.writes_enabled

Revision ID: 4f913b93ef9a
Revises: c4dbc62ca2a9
Create Date: 2026-06-03 18:55:17.905280

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f913b93ef9a"
down_revision: str | Sequence[str] | None = "c4dbc62ca2a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("devices", schema=None) as batch_op:
        # sa.true() renders the dialect-correct boolean literal (`true` on
        # Postgres, `1` on SQLite); a bare sa.text('1') is rejected by Postgres
        # as an integer default on a boolean column.
        batch_op.add_column(
            sa.Column("writes_enabled", sa.Boolean(), server_default=sa.true(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.drop_column("writes_enabled")

    # ### end Alembic commands ###
