"""add change_request version_id + updated_at (CON-1/CON-3)

Revision ID: abf3c6c84bf9
Revises: 04844e5d9aae
Create Date: 2026-05-30 21:15:48.645306

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abf3c6c84bf9"
down_revision: str | Sequence[str] | None = "04844e5d9aae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("change_requests", schema=None) as batch_op:
        # server_default='1' backfills existing rows so the NOT NULL add is safe.
        # SQLAlchemy's optimistic-concurrency counter (version_id_col) takes over
        # the increment from the application layer once rows are loaded/updated.
        batch_op.add_column(
            sa.Column("version_id", sa.Integer(), nullable=False, server_default="1")
        )
        # updated_at backfilled to CURRENT_TIMESTAMP for existing rows; the model
        # carries onupdate=now() so subsequent UPDATEs bump it (CON-3 heartbeat).
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("change_requests", schema=None) as batch_op:
        batch_op.drop_column("updated_at")
        batch_op.drop_column("version_id")

    # ### end Alembic commands ###
